name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  buildu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build on Ubuntu
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
      # Artifact name
        name: artifactu # optional, default is artifact
      # A file, directory or wildcard pattern that describes what to upload
        path: target/release/guessing_game

  buildw:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build on Windows
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
      # Artifact name
        name: artifactw # optional, default is artifact
      # A file, directory or wildcard pattern that describes what to upload
        path: target\release\guessing_game.exe
      # The desired behavior if no files are found using the provided path.

  buildm:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build on MacOs
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
      # Artifact name
        name: artifactm # optional, default is artifact
      # A file, directory or wildcard pattern that describes what to upload
        path: target/release/guessing_game
